# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/osher/Vivado_Projects/AXIL_LED_SW_BD/AXIL_LED_SW_BD.srcs/sources_1/bd/base/ip/base_auto_pc_12/base_auto_pc_12.xci
# IP: The module: 'base_auto_pc_12' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/osher/Vivado_Projects/AXIL_LED_SW_BD/AXIL_LED_SW_BD.srcs/sources_1/bd/base/ip/base_auto_pc_12/base_auto_pc_12_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_auto_pc_12'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/osher/Vivado_Projects/AXIL_LED_SW_BD/AXIL_LED_SW_BD.srcs/sources_1/bd/base/ip/base_auto_pc_12/base_auto_pc_12.xci
# IP: The module: 'base_auto_pc_12' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/osher/Vivado_Projects/AXIL_LED_SW_BD/AXIL_LED_SW_BD.srcs/sources_1/bd/base/ip/base_auto_pc_12/base_auto_pc_12_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_auto_pc_12'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
