# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/xdc.xdc

# Block Designs: bd/base/base.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base || ORIG_REF_NAME==base} -quiet] -quiet

# IP: bd/base/ip/base_ps7_0_0/base_ps7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_ps7_0_0 || ORIG_REF_NAME==base_ps7_0_0} -quiet] -quiet

# IP: bd/base/ip/base_ps7_0_axi_periph1_0/base_ps7_0_axi_periph1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_ps7_0_axi_periph1_0 || ORIG_REF_NAME==base_ps7_0_axi_periph1_0} -quiet] -quiet

# IP: bd/base/ip/base_rst_ps7_0_fclk0_0/base_rst_ps7_0_fclk0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rst_ps7_0_fclk0_0 || ORIG_REF_NAME==base_rst_ps7_0_fclk0_0} -quiet] -quiet

# IP: bd/base/ip/base_axi_led_switch_0_0/base_axi_led_switch_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_led_switch_0_0 || ORIG_REF_NAME==base_axi_led_switch_0_0} -quiet] -quiet

# IP: bd/base/ip/base_s00_regslice_14/base_s00_regslice_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_s00_regslice_14 || ORIG_REF_NAME==base_s00_regslice_14} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_12/base_auto_pc_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_12 || ORIG_REF_NAME==base_auto_pc_12} -quiet] -quiet

# XDC: bd/base/base_ooc.xdc
